### ISSUE TITLE
skill points menu is broken

### ISSUE THREAD

**Issue by Rrhyast** [pierre-josselin/payday-2-ultimate-trainer-5#17] opened 2022-03-31 00:17 UTC
it set skill points to zero or negative

**Comment by pierre-josselin** [comment] 2022-03-31 09:26
@Rrhyast

I can't reproduce the issue.

Could you provide me some additional informations:

- What version of the mod are you using
- What is your level
- How many skill points have you spent in the skill tree
- How many skill points you have set in the skill points menu
- What other mods do you use

**Comment by Rrhyast** [comment] 2022-03-31 12:37
> @Rrhyast
> 
> I can't reproduce the issue.
> 
> Could you provide me some additional informations:
> 
> * What version of the mod are you using
> * What is your level
> * How many skill points have you spent in the skill tree
> * How many skill points you have set in the skill points menu
> * What other mods do you use

-  5.2.0
-  100 / Infamy D
-  Its random, sometimes it set to 300, 400, 500, 700 &... and never recharge
- between 100 & 500 & 700 & 9999999999999.... but never set properly
-  nothing just ultimate trainer

**Comment by pierre-josselin** [comment] 2022-03-31 13:21
@Rrhyast

Thank you for the additional information.

Unfortunately, even if I put my game in the same conditions as you, I can't reproduce the issue : 

![image](https://user-images.githubusercontent.com/70814177/161062545-9c98c612-78c7-4c41-8bf3-16f7fac62797.png)

![image](https://user-images.githubusercontent.com/70814177/161062616-bb922bad-c27d-42a2-9131-c67f017a5d00.png)

![image](https://user-images.githubusercontent.com/70814177/161062733-e58016cb-7cc7-4ab6-9131-1850ed66ab85.png)

You could try to :

- Reset your skill tree
- Set your level to 0
- Set skill points hack to 0
- Disable skill points hack
- Restart the game

And check if it works again.

If it still doesn't work, try to install version [5.0.0-alpha](https://github.com/pierre-josselin/payday-2-ultimate-trainer-5/releases/tag/5.0.0-alpha) and please tell me if it works.

**Comment by Rrhyast** [comment] 2022-03-31 22:45
> @Rrhyast
> 
> Thank you for the additional information.
> 
> Unfortunately, even if I put my game in the same conditions as you, I can't reproduce the issue :
> 
> ![image](https://user-images.githubusercontent.com/70814177/161062545-9c98c612-78c7-4c41-8bf3-16f7fac62797.png)
> 
> ![image](https://user-images.githubusercontent.com/70814177/161062616-bb922bad-c27d-42a2-9131-c67f017a5d00.png)
> 
> ![image](https://user-images.githubusercontent.com/70814177/161062733-e58016cb-7cc7-4ab6-9131-1850ed66ab85.png)
> 
> You could try to :
> 
> * Reset your skill tree
> * Set your level to 0
> * Set skill points hack to 0
> * Disable skill points hack
> * Restart the game
> 
> And check if it works again.
> 
> If it still doesn't work, try to install version [5.0.0-alpha](https://github.com/pierre-josselin/payday-2-ultimate-trainer-5/releases/tag/5.0.0-alpha) and please tell me if it works.

I just found a way to avoid this issue and max out skill tree, I set skill points to 690 and it worked fine. if add additional info to set amount of the options like level, infamy, and skill points in help so much.

**Comment by pierre-josselin** [comment] 2022-03-31 23:00
@Rrhyast

Ah yes, if you set more than 690 skill points, the mod will ignore it.

I will add a message to avoid confusion.

**Comment by pierre-josselin** [comment] 2022-03-31 23:09
![image](https://user-images.githubusercontent.com/70814177/161163829-886b340b-55f0-417d-836e-3e4cd42b1467.png)

**Comment by pierre-josselin** [comment] 2022-03-31 23:09
You can close this issue if it's good for you.

**Closed** 2022-03-31 23:45 UTC
Labels: bug
